name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref }}
    steps:
      - name: Get Branch
        run: echo "${{ github.ref }}"
      - name: Get Secret
        run: echo "${{ secrets.DB_USERNAME }}
