name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.ref_name }}
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Get Branch
        run: echo "Branch ${{ github.ref_name }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Grant execute permission for gradlew
        run: chmod +x mvnw ./mvnw
      - name: Compile with Maven
        run: mvn -B compile --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  docker:
    needs: builds
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 041271/spring-actions
          tags: v2, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: docker
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Remote SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo $(sudo docker images)
            sudo docker pull 041271/spring-actions:latest
            sudo docker run -d --name spring-actions -p 8080:8080 041271/spring-actions:latest
            echo $(sudo docker images)
