name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-latest
    environment:
      name: master
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Get Branch Base
        run: echo "BRANCH ${{ github.base_ref }}"
      - name: Get Branch Ref
        run: echo "BRANCH ${{ github.ref }}"
      - name: Get Branch Name
        run: echo "BRANCH ${{ github.ref_name }}"
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for gradlew
        run: chmod +x mvnw ./mvnw
      - name: Compile with Maven
        run: mvn -B compile --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml

