name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-latest
    environment:
      name: master
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Get Branch
        run: echo "${{ github.ref }}"
      - name: Get Secret
        run: echo "${{ secrets.DB_USERNAME }}"
      - name: Get Environment Variable
        run: echo "DB_PORT ${{ env.DB_PORT }}"
