name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "${{ github.ref }}"
