name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
jobs:
  builds:
    runs-on: ubuntu-latest
    environment:
      name: master
    steps:
      - name: Get Branch
        run: echo "${{ github.ref }}"
      - name: Get Secret
        run: echo "${{ secrets.DB_USERNAME }}"
      - name: Get Environment Variable
        run: echo "${{ env.DB_PORT }}"
